apiVersion: apps/v1
kind: Deployment
metadata:
  name: helix-participant-deployment
  labels:
    app: participant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant
  template:
    metadata:
      labels:
        app: participant
    spec:
      volumes:
      - name: host-volume
        hostPath:
          path: /home/docker
      containers:
      - image: rabashizade/helix-core:1.3
        name: helix-participant
        volumeMounts:
        - mountPath: /tmp
          name: host-volume
        command: ["/bin/sh", "-c", "/target/helix-core-pkg/bin/start-helix-participant.sh --zkSvr helix-zookeeper-service-internal:2199 --cluster MYCLUSTER --port 12900 --stateModelType MasterSlave 2>&1 > /tmp/participant.log"]
