apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      volumes:
      - name: host-volume
        hostPath:
          path: /home/docker
      containers:
      - image: rabashizade/helix-core:1.3
        name: helix-zookeeper
        volumeMounts:
        - mountPath: /tmp
          name: host-volume
        command: ["/bin/sh", "-c", "/target/helix-core-pkg/bin/start-standalone-zookeeper.sh 2199 2>&1 > /tmp/zookeeper.log"]
---
apiVersion: v1
kind: Service
metadata:
  name: helix-zookeeper-service-external
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
  - protocol: TCP
    port: 2199
    targetPort: 2199
    nodePort: 30100
---
apiVersion: v1
kind: Service
metadata:
  name: helix-zookeeper-service-internal
spec:
  selector:
    app: zookeeper
  ports:
  - protocol: TCP
    port: 2199
    targetPort: 2199
